import type { Metadata } from 'next';

import { ClientLayout } from './clientLayout';
import './globals.css';
import './styles.scss';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className="font-sans antialiased">
				<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	);
}
